### ISSUE TITLE
Remove Schoolbox current period and implement own

### ISSUE THREAD

**Issue by 42willow** [schooltape/schooltape#193]
The current implementation of Schoolbox's "current period" doesn't update with time, it requires a page refresh. This is confusing and misleading.
A solution for this would be to create a plugin and do this ourself.

could inject something like this
```css
.timetable-subject-active:before {
  display: none;
}
timetable-subject-active > div.timetable-subject {
  height: 126px !important;
}
```
(to revert their changes)

then make own modifications that update without a page refresh
