### ISSUE TITLE
Refactor CSS to explicitly use Schoolbox component classes

### ISSUE THREAD

**Issue by 42Willow** [schooltape/schooltape#84]
For example:
```css
.Component_Homepage_CountdownController.component-container,
.Schoolbox_Resource_Textbox_Component_Homepage_Controller.component-container,
.Component_Homepage_SocialStreamController.component-container,
.Component_Homepage_SlideshowController.component-container,
.Component_Homepage_AudioController.component-container,
.Component_Homepage_TeachersController.component-container,
.Component_Homepage_ClassListController.component-container,
.Schoolbox_Comms_News_Component_Homepage_Controller.component-container,
.Component_Homepage_LinkListController.component-container,
.Component_Homepage_FileListController.component-container,
.Schoolbox_Learning_Assessment_Component_Homepage_Outline_Controller.component-container,
.Schoolbox_Learning_Assessment_DueWork_Component_Homepage_Controller.component-container,
.Schoolbox_Learning_Assessment_Task_Component_Homepage_Controller.component-container,
.Schoolbox_Learning_Assessment_Quiz_Component_Homepage_Controller.component-container {
  background: hsl(var(--ctp-accent));
  border-radius: 10px;
} 
```

The different classes can be found inside Schoolbox's `core.css` file
